name: appsSkybox3
packages:
  - packages/**
environment:
  sdk: '>=3.0.0 <4.0.0'
scripts:
  bootstrap:
    run: melos bootstrap
  clean:
    run: melos exec -- flutter clean
  pub_get:
    run: melos exec -- flutter pub get
  build_runner: 
    run: melos exec -- flutter pub run build_runner build --delete-conflicting-outputs 
  test: 
    run: melos exec -- flutter test 
  lint: 
    run: melos exec -- flutter analyze 
  format: 
    run: melos exec -- flutter format .
  new:
    # Accept positional arguments
    run: bash novoProjeto.sh $1
    description: "Create a new project based on the modelo template. Usage: melos run new <project-name>"